version: "3.9"
services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
  watcher:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
